In [12]:
import pandas as pd

df = pd.read_csv('소방청_화재발생 정보_20241231.csv', encoding='cp949')
print(df.shape)
df.head()

(191510, 15)

,화재발생년원일,시도,시군구,화재유형,발화요인대분류,발화요인소분류,인명피해(명)소계,사망,부상,재산피해소계,부동산,동산,장소대분류,장소중분류,장소소분류
0,2020-01-01 0:03,전북특별자치도,익산시,"건축,구조물",부주의,기타(부주의),0,0,0,171,171.0,0.0,생활서비스,음식점,"치킨,족발"
1,2020-01-01 0:33,서울특별시,성북구,기타(쓰레기 화재등),부주의,담배꽁초,0,0,0,326,0.0,326.0,기타,야외,쓰레기
2,2020-01-01 0:35,경상북도,영덕군,기타(쓰레기 화재등),부주의,담배꽁초,0,0,0,0,NaN,NaN,기타,야외,기타야외
3,2020-01-01 0:40,충청북도,옥천군,"자동차,철도차량",기계적 요인,"과열, 과부하",0,0,0,2640,0.0,2640.0,"자동차,철도차량",자동차,승용자동차
4,2020-01-01 0:59,부산광역시,금정구,"자동차,철도차량",미상,미상,0,0,0,7904,179.0,7725.0,"자동차,철도차량",자동차,오토바이

In [13]:
# 인명피해(명)소계가 1 이상이면 1, 아니면 0 → 인명피해 발생 여부
df['인명피해_발생여부'] = (df['인명피해(명)소계'] > 0).astype(int)

df['인명피해_발생여부'].value_counts(normalize=True)  # 불균형 체크

인명피해_발생여부
0    0.955543
1    0.044457
Name: proportion, dtype: float64

In [14]:
df['화재발생년원일'] = pd.to_datetime(df['화재발생년원일'])

df['발생_월'] = df['화재발생년원일'].dt.month        # 계절 확인용
df['발생_시간'] = df['화재발생년원일'].dt.hour           # 시간대
df['발생_요일'] = df['화재발생년원일'].dt.dayofweek   # 0=월요일, 6=일요일

In [15]:
df.head()

,화재발생년원일,시도,시군구,화재유형,발화요인대분류,발화요인소분류,인명피해(명)소계,사망,부상,재산피해소계,부동산,동산,장소대분류,장소중분류,장소소분류,인명피해_발생여부,발생_월,발생_시간,발생_요일
0,2020-01-01 00:03:00,전북특별자치도,익산시,"건축,구조물",부주의,기타(부주의),0,0,0,171,171.0,0.0,생활서비스,음식점,"치킨,족발",0,1,0,2
1,2020-01-01 00:33:00,서울특별시,성북구,기타(쓰레기 화재등),부주의,담배꽁초,0,0,0,326,0.0,326.0,기타,야외,쓰레기,0,1,0,2
2,2020-01-01 00:35:00,경상북도,영덕군,기타(쓰레기 화재등),부주의,담배꽁초,0,0,0,0,NaN,NaN,기타,야외,기타야외,0,1,0,2
3,2020-01-01 00:40:00,충청북도,옥천군,"자동차,철도차량",기계적 요인,"과열, 과부하",0,0,0,2640,0.0,2640.0,"자동차,철도차량",자동차,승용자동차,0,1,0,2
4,2020-01-01 00:59:00,부산광역시,금정구,"자동차,철도차량",미상,미상,0,0,0,7904,179.0,7725.0,"자동차,철도차량",자동차,오토바이,0,1,0,2

In [16]:
# 컬럼 정리
drop_cols = ['인명피해(명)소계', '사망', '부상', '재산피해소계', '부동산', '동산', '화재발생년원일', '장소중분류', '장소소분류', '시군구']
df = df.drop(columns=drop_cols)

In [17]:
df.head()

,시도,화재유형,발화요인대분류,발화요인소분류,장소대분류,인명피해_발생여부,발생_월,발생_시간,발생_요일
0,전북특별자치도,"건축,구조물",부주의,기타(부주의),생활서비스,0,1,0,2
1,서울특별시,기타(쓰레기 화재등),부주의,담배꽁초,기타,0,1,0,2
2,경상북도,기타(쓰레기 화재등),부주의,담배꽁초,기타,0,1,0,2
3,충청북도,"자동차,철도차량",기계적 요인,"과열, 과부하","자동차,철도차량",0,1,0,2
4,부산광역시,"자동차,철도차량",미상,미상,"자동차,철도차량",0,1,0,2

In [18]:
df.to_csv('fire.csv', encoding='utf-8-sig', index=False)